# Configuration file for JuliaFormatter.jl, see: https://domluna.github.io/JuliaFormatter.jl/stable/config/
always_for_in = true
always_use_return = true
margin = 120
remove_extra_newlines = true
separate_kwargs_with_semicolon = true
short_to_long_function_def = true
long_to_short_function_def = true
whitespace_typedefs = true
