julia_version = "1.11.0"
manifest_format = "2.0"
project_hash = "32cffdc8f82d195594fe19f030bb5208ae78e90d"

[[deps.Gurobi]]
deps = ["Gurobi_jll", "Libdl", "MathOptInterface"]
git-tree-sha1 = "53cc56f49295c6b41da670fcf0e0cd812c9580c7"
uuid = "2e9cd046-0924-5485-92f1-d5272153d98b"
version = "1.3.1"

[[deps.Gurobi_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl"]
git-tree-sha1 = "179143cef0916daf0afc83a629501da3fa76af4d"
uuid = "c018c7e6-a5b0-4aea-8f80-9c1ef9991411"
version = "11.0.2+2"

[[deps.HiGHS]]
deps = ["HiGHS_jll", "MathOptInterface", "PrecompileTools", "SparseArrays"]
git-tree-sha1 = "3a7f13068f77fa54edd9589f762c600a22679bf7"
uuid = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
version = "1.9.3"

[[deps.HiGHS_jll]]
deps = ["Artifacts", "CompilerSupportLibraries_jll", "JLLWrappers", "Libdl", "Zlib_jll"]
git-tree-sha1 = "1f240e0fb1c4cdf39bca5d3881d1758263931ccb"
uuid = "8fd58aa0-07eb-5a78-9b36-339c94fd15ea"
version = "1.7.2+0"

[[deps.JuMP]]
deps = ["LinearAlgebra", "MacroTools", "MathOptInterface", "MutableArithmetics", "OrderedCollections", "PrecompileTools", "Printf", "SparseArrays"]
git-tree-sha1 = "c95f443d4641b128d626a429b51d5185050135b5"
uuid = "4076af6c-e467-56ae-b986-b466b2749572"
version = "1.23.2"

[[deps.MathOptInterface]]
deps = ["BenchmarkTools", "CodecBzip2", "CodecZlib", "DataStructures", "ForwardDiff", "JSON", "LinearAlgebra", "MutableArithmetics", "NaNMath", "OrderedCollections", "PrecompileTools", "Printf", "SparseArrays", "SpecialFunctions", "Test", "Unicode"]
git-tree-sha1 = "5b246fca5420ae176d65ed43a2d0ee5897775216"
uuid = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
version = "1.31.2"
